create table person (
    id int generated by default as identity PRIMARY KEY,
    full_name text UNIQUE NOT NULL,
    year_of_birth int
);

create table book (
    id int generated by default as identity PRIMARY KEY,
    title varchar(100) NOT NULL,
    author text,
    year_of_publication int,
    person_id int REFERENCES person (id) ON DELETE SET NULL
);