create table Sensor (
    id int generated by default as identity PRIMARY KEY,
    "name" varchar(30) NOT NULL UNIQUE
);

create table Measurement (
    id int generated by default as identity PRIMARY KEY,
    "value" numeric(3, 1) NOT NULL,
    raining boolean NOT NULL,
    sensor_name varchar(30) REFERENCES Sensor("name") NOT NULL,
    created_at timestamp
);